exadel-inc/esl

README.md
src/modules/draft/esl-carousel/core/esl-carousel.ts
src/modules/draft/esl-carousel/plugin/esl-carousel-autoplay.plugin.ts
src/modules/draft/esl-carousel/plugin/esl-carousel-dots.plugin.ts
src/modules/draft/esl-carousel/plugin/esl-carousel-link.plugin.ts
src/modules/esl-base-element/core.ts
src/modules/esl-base-element/core/esl-base-element.ts
src/modules/esl-base-element/test/base-element.test.ts
src/modules/esl-base-popup/core/esl-base-popup.ts
src/modules/esl-image/core/esl-image.ts
src/modules/esl-media/core/esl-media-manager.ts
src/modules/esl-media/core/esl-media.ts
src/modules/esl-panel/core/esl-panel-stack.ts
src/modules/esl-panel/core/esl-panel.ts
src/modules/esl-popup/core/esl-popup.ts
src/modules/esl-scrollable-tabs/core/esl-scrollable-tabs.ts
src/modules/esl-tab/core/esl-tab.ts
src/modules/esl-tab/core/esl-tabs-container.ts
src/modules/esl-trigger/core/esl-trigger.ts
test-server/views/pages/esl-accordion.html

BREAKING CHANGE:
- `ESLBasePopup` statechange events replaced with a separate `(before:)show/hide`
- `ESLBaseElement` no longer contains eventNs and $$fireNs methods
- Whole popups based component system no longer use event namespaces
- `transitionend` event of ESLPanel replaced with `after:show`/`after:hide`
- `statechange` event of ESLTrigger replaced with `change:active`

Tech: eventing massive updates for version 2.0.0

---

src/modules/esl-image/README.md
src/modules/esl-image/core/esl-image.ts

Not sure that we need to do that, but it looks like that's the only possible way to check SVGs state, as they have naturalWIdth = naturalHeight = 0 in Gecko in case the width and height are not specified in SVG content.

fix(esl-image): svg loading check update

---

src/modules/esl-toggleable/core/esl-toggleable.ts

Most likely will be revised soon, but it sounds like auto-clear in the low-level method is not good idea (at least),

fix: activator should be available after hide

---

src/modules/esl-image/core/esl-image-strategies.ts
src/modules/esl-image/core/esl-image.ts
src/modules/esl-media-query/core/esl-media-query.ts
src/modules/esl-media-query/test/esl-media-query.test.ts

BREAKING CHANGE: 
ESLMediaQuery API no longer provide meta information like DPR or type of expected device
Preparation for #232 updates.

refactor: esl-media-query cleanup for API and usages

---

src/modules/esl-utils/decorators/memoize.ts
src/modules/esl-utils/misc/object.ts

Update memoize decorator inner logic to use simple value caching for members simple property so 
- Static method -> replace to memo-decorated method
- Static getter -> replace getter function to memo-decorated
- object method -> memo-decorated own property method
- object getter -> own property computed value _(**new**)_

feat: light memoize decorator

---

src/modules/esl-footnotes/core/esl-footnotes.less
src/modules/esl-footnotes/core/esl-footnotes.ts
src/modules/esl-note/core/esl-note.ts

Communication between notes and footnotes was broken during the last big PR.
This fixes the issue.
Also changed character for footnotes button "Return to note" due to its absence in fonts on some platforms.

fix(esl-note): fix broken connection between esl-note and esl-footnotes

---

src/modules/esl-utils/async/debounce.ts
src/modules/esl-utils/async/delayed-task.ts
src/modules/esl-utils/async/promise.ts
src/modules/esl-utils/async/raf.ts
src/modules/esl-utils/async/test/debounce.test.ts
src/modules/esl-utils/async/test/promise.test.ts
src/modules/esl-utils/async/test/throttle.test.ts
src/modules/esl-utils/async/throttle.ts

- fix unstable tests in the async directory
- update promise utils with functional export (to achieve tree shakable structure) 
- fix missing leading tryUntill callback call
Note: PromiseUtils is still available and has no API changes

feat(esl-utils): promise utils fixes & test updates

---

src/modules/esl-footnotes/core/esl-footnotes-data.ts
src/modules/esl-footnotes/core/esl-footnotes.ts
src/modules/esl-footnotes/core/esl-note.ts

Fixed:
- ESLNote lost tooltip text (after cloning element)
- ESLFootnotes breaks the order of notes
- ESLFootnotes duplicate notes if they were cloned

fix(esl-footnotes): ESLNote lost tooltip text and ESLFootnotes duplicate notes and break order

---

package-lock.json
package.json
src/modules/esl-base-element/core/esl-base-element.ts
src/modules/esl-utils/environment/device-detector.ts

Version 4.4.2 has a more detailed type control, so a couple of errors appeared that were hidden in the previous versions.
Both are local variables that do not affect export API, so just made them any for now (there is no sense to describe a type for a couple of usages that goes exactly near the variable definition).

chore(patch): update TS version to 4.4.2, related fixes

---

src/modules/esl-utils/dom/scroll.ts

Corrects the scrollIntoViewAsync() method signature so that it exactly matches the native one.

fix(esl-utils): scrollIntoViewAsync() method signature

---

src/modules/esl-footnotes/core/esl-note.ts
src/modules/esl-utils/dom/scroll.ts

In scope:
- renamed scrollIntoViewAsync() method with scrollIntoView()
- added to scrollIntoView() ability to detect when scrolling stops
Using this method comes in handy when you use smooth scrolling to scroll through an element in the scope and you need to know exactly when the element is visible and scrolling has finished.

feat: add ability to scrollIntoView to detect when scrolling stops

---

pages/views/_layouts/popup.njk
pages/views/examples/popup.njk
src/modules/esl-popup/core/esl-popup-position.ts
src/modules/esl-popup/core/esl-popup.less
src/modules/esl-popup/core/esl-popup.ts

In the scope of this PR were made next changes:
- added new attribute offset-arrow to set up arrow position in percents of popups dimension size;
- added new attribute margin-arrow to set up the margin of the arrow in pixels to the edge of the popup;
- refactored popup styles to make it easier to position the arrow inside the popup;
- created a new mixin for popup arrow styles that takes into account the size and thickness of the arrow borders.

feat(esl-popup): add new feature to be able to set position of arrow on popup

---

src/modules/esl-footnotes/core/esl-footnotes.ts
src/modules/esl-tooltip/core/esl-tooltip.less
src/modules/esl-tooltip/core/esl-tooltip.ts
src/modules/esl-utils/dom/focus.ts

In scope of this PR:
- add focus out handling at esl-tooltip
- fix keydown events at esl-footnotes

feat(esl-footnotes): a few accessibility fixes

---

src/modules/esl-popup/core/esl-popup-position.ts
src/modules/esl-popup/core/esl-popup.shape.ts
src/modules/esl-popup/core/esl-popup.ts

In scope of this PR:
- added `disable-activator-observation` attribute to let popup leaves viewport without hiding
- added new `fit-on-major` value for the behavior attribute so that the popup update its position in order to fit on the major axis only
- added new `fit-on-minor` value for the behavior attribute so that the popup update its position in order to fit on the minor axis only
- added RTL support, resulting in a popup mirrored relative to the major axis
- updated TSX shapes
- refactor code to achieve the best performance during popup position updating

feat(esl-popup): couple new features and refactoring

---

src/modules/esl-toggleable/core/esl-toggleable.ts

> added handler for esl:show:request at esl-toggleable that allows all components based on toggleable to show content when content requested showing

feat(esl-toggleable): add ootb handler for esl:show:request

---

src/modules/esl-utils/async/promise.ts
src/modules/esl-utils/async/test/promise.test.ts

Created extended version of `promisifyTimeout` method #858
Closes: #858

feat(esl-utils): update promisifyTimeout with extended syntax support

---

pages/src/navigation/sidebar/sidebar.ts
src/modules/esl-base-element/core.ts
src/modules/esl-tab/core/esl-tab.ts
src/modules/esl-utils/decorators/attr.ts
src/modules/esl-utils/decorators/bool-attr.ts
src/modules/esl-utils/decorators/json-attr.ts
src/modules/esl-utils/decorators/test/attr.test.ts
src/modules/esl-utils/decorators/test/bool-attr.test.ts
src/modules/esl-utils/decorators/test/json-attr.test.ts

fix(esl-utils): move attribute decorators to the `esl-utils`

---

src/modules/esl-panel-group/core/esl-panel-group.ts

Fix `esl:before:hide` bubbling from uncontrolled toggleables

fix(esl-panel-group): fix esl:before:hide bubbling from uncontrolled toggleables

---

src/modules/esl-base-element/core/esl-base-element.ts
src/modules/esl-utils/decorators/test/listen.test.ts
src/modules/esl-utils/dom/events/listener.ts
src/modules/esl-utils/dom/events/test/listener.test.ts
src/modules/esl-utils/dom/events/test/utils.test.ts
src/modules/esl-utils/dom/events/utils.ts
src/modules/esl-utils/misc/object/compare.ts
src/modules/esl-utils/misc/object/test/compare.test.ts

Preparation for mixin components, see https://github.com/exadel-inc/esl/pull/816/commits/33ce7aa5c3625266b3900ed8d88f012f847945a6 
- `ESLEventListener.descriptors` moved to `EventUtils.descriptors`
- add ability to subscribe handler with additional descriptor data
- remove subscribe all descriptors functionality

feat(esl-utils): rework subscription API

---

src/modules/draft/esl-carousel/plugin/esl-carousel-touch.plugin.ts
src/modules/esl-scrollbar/core/esl-scrollbar.ts
src/modules/esl-utils/dom/events/misc.ts
src/modules/esl-utils/dom/events/test/misc.test.ts
src/modules/esl-utils/dom/test/events.test.ts

BREAKING CHANGE: rename `offsetPoint` to `getOffsetPoint` and `touchPoint` to `getTouchPoint`

fix(esl-utils): rename some event/misc utils

---

pages/views/examples/footnotes.njk
src/modules/esl-footnotes/core/esl-note.ts
src/modules/esl-popup/core/esl-popup.ts

In the scope of this PR:
- add intersectionMargin param to esl-popup to configure rootMargin for the popup activator observer
- add intersectionMargin attribute to esl-note to configure and transfer it to esl-tooltip

feat(esl-popup): add configurable rootMargin for the popup activator observer

---

pages/views/examples/toggleable.njk
src/modules/esl-trigger/README.md
src/modules/esl-trigger/core/esl-trigger.shape.ts
src/modules/esl-trigger/core/esl-trigger.ts

In the scope of this PR I made ability to define values of aria-label for both esl-trigger states via `a11y-label`.
Example:
a11y-label="{active: 'collapse', inactive: 'expand'}"

Feat(esl-trigger): add aria-label support

---

src/modules/esl-utils/decorators/prop.ts
src/modules/esl-utils/decorators/test/prop.test.ts

BREAKING CHANGE: `@prop` signature changed
`prop(value?: any, prototypeConfig: OverrideDecoratorConfig = {})`

feat(esl-utils): simplify and extend `@prop` decorator

---

src/modules/esl-utils/misc/object/test/copy.test.ts
src/modules/esl-utils/misc/object/test/merge.test.ts

Added tests to detect prototype pollution vulnerabilities ([Analysis and Exploitation of Prototype Pollution attacks](https://blog.0daylabs.com/2019/02/15/prototype-pollution-javascript/))

test(esl-utils): add tests to detect prototype pollution vulnerabilities

---

src/modules/esl-image/core/esl-image-strategies.ts
src/modules/esl-image/test/esl-image.test.ts
src/modules/esl-image/test/xmlHttpRequest.mock.ts
src/modules/esl-utils/all.ts
src/modules/esl-utils/dom/sanitize.ts
src/modules/esl-utils/dom/test/sanitize.test.ts

In scope of this PR:
- create esl-utils dom helper to sanitize html
- modify esl-image to prevent DOM XSS vulnerabilities
Closes: #1058

Feat(esl-utils, esl-image): sanitize html to prevent DOM XSS vulnarabilities

---

jest.config.js

The small Jest config improvements speed up running tests two times.
Before:
After:

chore: tests speed-up

---

src/modules/esl-utils/dom/scroll/parent.ts
src/modules/esl-utils/dom/scroll/test/parent.test.ts
src/modules/esl-utils/dom/scroll/test/utils.test.ts
src/modules/esl-utils/dom/scroll/utils.ts

In the scope of this PR:
- covered scroll utils with tests (except scrollIntoView function, because it's implementation will be changed in future updates);
- renamed function from 'isScrollParent' to 'isScrollable', because it didn't actually check element's parent element;
- replaced initiatorSet with initiatorMap in order for it to remember initiator target.

test(esl-utils): scroll utils code improvements and scroll utils test coverage

---

src/modules/esl-utils/dom/events/target.ts
src/modules/esl-utils/dom/events/test/target.test.ts

In the scope of this PR I extended SynteticEventTarget to separate events by their type.
The end result repeats implementation of native event storage.
Code base tests were extended and refactored.

feat(esl-utils): extend SynteticEventTarget with ability to separate events enhancement

---

src/modules/esl-base-element/core.ts
src/modules/esl-mixin-element/core.ts
src/modules/esl-utils/decorators/listen.ts
src/modules/esl-utils/decorators/test/listen.test.ts
src/modules/esl-utils/dom/events/listener.ts
src/modules/esl-utils/dom/events/test/listener.test.ts
src/modules/esl-utils/dom/events/test/utils.test.ts

In bounds of this PR:
1. Add a check to prevent an empty targets listener from subscription
2. Make able to inherit event listener method definition meta from superclass with a short version of `@listen` decorator
3. (cosmetic) `prop` decorator added to the `esl-mixin-element` and `esl-base-element` modules export
4. cover new functionality by tests
The following inheritance cases are available :
For now the following syntax is available:
```
class Super {
@listen({...})
onEvent() {}
}
// Unsubscribe option 
class ClassA {
// overrides without listener definition
onEvent() {}
}
// Replaces Super definition
class ClassB {
@listen({...})
onEvent() {}
}
// Inherit and merge Super event listener definition
class ClassC {
@listen({inherit: true, ...})
onEvent() {}
}
// Just inherit Super event …
```

feat(esl-utility): event listener subscription logic fix and ability to inherit listener definition

---

.stylelintrc.yml
pages/src/banner/banner.less
pages/src/common/accordion.less
pages/src/common/alert.less
pages/src/common/badge.less
pages/src/common/buttons.less
pages/src/common/dropdown-menu.less
pages/src/common/forms.less
pages/src/common/helpers.less
pages/src/common/markdown.less
pages/src/common/reboot.less
pages/src/common/tabs.less
pages/src/common/typography.less
pages/src/landing/marquee/marquee.less
pages/src/landing/overview/overview.less
pages/src/navigation/footer/footer.less
pages/src/navigation/header/header-search.less
pages/src/navigation/sidebar/sidebar-content.less
src/modules/draft/esl-carousel/plugin/esl-carousel-dots.less
src/modules/esl-forms/esl-select-list/core/esl-select-item.less
src/modules/esl-forms/esl-select/core/esl-select-dropdown.less
src/modules/esl-image/core/esl-image-container.less
src/modules/esl-popup/core/esl-popup.less

In this PR I added a number-leading-zero rule to stylelint config to disallow a leading zero for fractional numbers less than 1.
The following pattern is considered as a problem:
a { line-height: 0.5; }
The following pattern isn't considered as a problem:
a { line-height: .5; }
Closes #1125

code style: disallow number leading zero

---

jest.config.js

Type checking returned as it needs to be performed while the full run of the unit tests.

chore: return back type-checking for tests

---

src/modules/esl-tab/core/esl-tabs.ts

BREAKING-CHANGE: listeners extended from `ESLTabs` should now use `@listen` annotation to work correctly

feat(esl-tabs): `ESLTabs` migrated to `ESLEventListeners`

---

src/modules/esl-base-element/test/element.listener.test.ts
src/modules/esl-event-listener/core/listener.ts
src/modules/esl-event-listener/core/types.ts
src/modules/esl-mixin-element/test/mixin.listener-herpers.test.ts
src/modules/esl-mixin-element/test/mixin.listener.test.ts

For purpose of improving debugging, now event subscription does not wrap handler function if there is no need (`once` marker or delegation (`selector`))

feat(esl-event-listener): improve `ESLEventListener` object to have exact handler for simple subscriptions

---

pages/views/redirect/esl-utils.njk
pages/views/redirect/utils.njk

The permalink for `/utils/esl-utils/` was added

Fix redirect for `/utils/esl-utils/`

---

src/modules/esl-popup/core/esl-popup.ts

After discussion with @ala-n it was decided that public visibility on some of the methods of esl-popup is considered a bug

fix(esl-popup): protected methods visibility

---

src/modules/esl-event-listener/core/listener.ts

- fix restrictions on the host passing to `TraversingQuery` (does not restrict host type due to availability of making absolute queries)
- remove the restriction of host key access due to partial typings of `Object.hasOwnProperty.call` instruction (will be removed with `Obgect.hasOwn` integration)

fix(esl-event-listener): fix typechecking for TS5

---

src/modules/esl-base-element/core/esl-base-element.ts
src/modules/esl-event-listener/core.ts
src/modules/esl-event-listener/core/api.ts
src/modules/esl-event-listener/core/targets/resize.adapter.event.ts
src/modules/esl-event-listener/core/targets/resize.adapter.ts
src/modules/esl-event-listener/core/types.ts
src/modules/esl-event-listener/test/targets/resize.test.ts
src/modules/esl-mixin-element/ui/esl-mixin-element.ts
src/modules/esl-utils/decorators/listen.ts

`ESLListenerEventMap` moved to the global namespace.
Closes: #1559

feat(esl-event-listener): improved `ESLResizeObserverTarget` API with a standardized `ESLElementResizeEvent`

---

src/modules/esl-utils/decorators/attr.ts
src/modules/esl-utils/decorators/bool-attr.ts
src/modules/esl-utils/decorators/json-attr.ts
src/modules/esl-utils/decorators/prop.ts

Upon implementation of showcase repository of JavaScript project that uses ESL (https://github.com/fshovchko/esl-decorators-test), it was discovered that some of our decorators do not work with babel. The most problematic ones were property decorators. For some reason, instance always had value set to 'undefined', and the prototype had the correct value. But because instance had 'undefined' value, the prototype value was always ignored.
It was discovered, the legacy decorators in Babel behave different than legacy decorators in TypeScript (https://github.com/babel/babel/issues/8864). For example:
- In Babel legacy decorators, they may receive an initializer property instead of a value property, but in TypeScript there is never an initializer property, only a value property.
- In …

fix(esl-utils): make ts decorators compatiable with babel

---

src/modules/esl-mixin-element/test/mixin.test.ts
src/modules/esl-mixin-element/ui/esl-mixin-registry.ts

Significant performance improvement of the mixin registration step by scoping the DOM invalidation to changed nodes and registered mixin type.
Numbers: -33% to time of total registration execution on (20 mixin types in consistent 3200 nodes tree). The boost is in linear dependency of the mixin count.

fix(esl-mixin-element): performance improvement

---

src/modules/esl-toggleable/core/esl-toggleable-dispatcher.ts
src/modules/esl-toggleable/core/esl-toggleable.ts

The scope of this PR is to resolve issue described in #1799 + updated error message for toggleable dispatcher. ESLint didn't like the extra declaration, so another way of fixing it may be:
```
if (!this.connected || newVal === oldVal) return;
const isOpen = this.hasAttribute('open');
switch (attrName) {
case 'open':
if (this.open === isOpen) return;
this.toggle(isOpen, {initiator: 'attribute', showDelay: 0, hideDelay: 0});
break;
```

fix(esl-togglable): open attribute change behavior

---

package.json

Removed redundant port definition from script command. The port number definition in the e11ty config is left.

chore: update watch:eleventy stating script

---

src/modules/esl-toggleable/core/esl-toggleable.ts
src/modules/esl-toggleable/test/toggleable.close-on.test.ts

Fix activator when close-on inner trigger click handled + test coverage for related functionality
Closes: #1852

fix(esl-toggleable): fix activator when close-on inner trigger click handled (#1852)

---

src/modules/esl-utils/dom/scroll.less
src/modules/esl-utils/dom/scroll/utils.ts

- `pseudo` scroll lock now uses padding hack instead of flexbox on the html level
- new `background` type of lock repeats `pseudo` but with much more lower default `z-index` for scrollbar stub

feat(esl-utils): `lockScroll` / `unlockScroll` methods reworked with no-scroll detection

---

src/modules/esl-event-listener/README.md
src/modules/esl-event-listener/core/targets/swipe.event.ts
src/modules/esl-event-listener/core/targets/swipe.target.ts
src/modules/esl-utils/dom/test/units.test.ts
src/modules/esl-utils/dom/units.ts

Add SwipeEventTarget to subscribe `swipe`, `swipe:left`, `swipe:right`, `swipe:up`, `swipe:down` events using `ESLEventUtils.subscribe` or `@listen` descriptor
Closes: #1809

feat(swipe-target): Add SwipeEventTarget

---

src/modules/esl-event-listener/core/targets/resize.adapter.ts
src/modules/esl-event-listener/test/targets/resize.test.ts

fix(esl-event-listener): `ESLResizeObserverTarget.for` handles no target cases silently (warning + null result)

---

.husky/pre-commit

Have you ever encountered a situation where you couldn't merge a branch because lint-staged had validated it? Say goodbye to self-managed merge messages and the frustration of rejections for code that isn't yours)

chore: ignore lint-staged action in case merge commit processing locally

---

src/modules/esl-share/core.ts
src/modules/esl-share/core/esl-share-button.ts
src/modules/esl-share/core/esl-share-list.ts
src/modules/esl-share/core/esl-share-popup-trigger.ts
src/modules/esl-share/core/esl-share-popup.ts
src/modules/esl-share/core/esl-share.ts
src/modules/esl-trigger/core/esl-trigger.ts

[ESL Share]: follow up (wave 1)

---

pages/views/examples/tabs.njk
src/modules/esl-panel-group/core/esl-panel-group.less

feat(esl-panel-group): add ability to enable match-height behavior for tabs height using `esl-tabs-equal-height` class

---

src/modules/esl-share/README.md
src/modules/esl-share/actions/copy-action.ts
src/modules/esl-share/buttons/copy.ts
src/modules/esl-share/core/esl-share-config.ts
src/modules/esl-share/test/actions/copy-action.test.ts
src/modules/esl-share/test/esl-share-button.test.ts
src/modules/esl-share/test/esl-share-config.test.ts

Plus: tech dept of renaming `alertText` to `copyAlertMsg`

fix(esl-share): fix merging of `additional`(nested) params when `ESLShareConfig.update` method is called

---

src/modules/esl-carousel/core/esl-carousel.renderer.ts
src/modules/esl-carousel/core/esl-carousel.slide.ts
src/modules/esl-carousel/core/esl-carousel.ts

feat: esl carousel add pre-active marker

---

.husky/commit-msg
.husky/pre-commit
.husky/pre-push
package.json

Update the Husky config to [v9.0.2](https://github.com/typicode/husky/releases/tag/v9.0.2)

chore(deps): update husky config

---

src/modules/esl-utils/async/microtask.ts
src/modules/esl-utils/async/test/microtask.test.ts

fix(microtask): fix argument list on next fn call

---

package-lock.json
site/package.json
site/src/localdev.less
site/src/localdev.ts
site/src/playground/export/lib.less
site/src/playground/export/lib.ts
site/src/playground/ui-playground.less
site/src/playground/ui-playground.ts
site/src/ui-playground/ui-playground.ts
site/webpack.config.js

Example of usage:
```html
<uip-root>
<script type="text/html" uip-snippet label="Mixin example">
The time is: <time time-inject-mixin></time>
</script>
<script type="text/html" uip-js-snippet label="Mixin example">
import {ESLMixinElement} from '@exadel/esl';
class TimeInjectMixin extends ESLMixinElement {
static get is() {
return 'time-inject-mixin';
}
connectedCallback() {
super.connectedCallback();
this.update();
}
update() {
this.$host.innerHTML = new Date().toLocaleTimeString();
this._timeout = setTimeout(() => this.update(), 1000);
}
}
TimeInjectMixin.register();
</script>
<uip-snippets class="uip-toolbar" dropdown-view="@xs"></uip-snippets>
<uip-preview isolation style="height: 50px"></uip-preview>
<uip-editor label="Source code (HTML)" collapsible copy></uip-editor>
<uip-editor …
```

chore(site): isolated playground base code 

---

.commitlintrc.yml
docs/COMMIT_CONVENTION.md
src/modules/esl-event-listener/test/targets/swipe.test.ts

refactor(lint): add commit lint scope validation

---

src/modules/esl-utils/decorators/attr.ts
src/modules/esl-utils/decorators/test/attr.test.ts
src/modules/esl-utils/dom/attr.ts
src/modules/esl-utils/dom/test/attr.test.ts

feat(esl-utils): extend `attr` decorator with inherit option

---

src/modules/esl-event-listener/README.md
src/modules/esl-event-listener/core/api.ts

Note: `ESLEventUtils.descriptors` is going to be reintroduced in 5.0.0
NOTE: It is a proper (not deprecated) way to use `ESLEventUtils.descriptors(host, {auto: true})` instead `ESLEventUtils.getAutoDescriptors`
See related 5.0.0 update ->  https://github.com/exadel-inc/esl/pull/2413

fix(esl-event-listener): `ESLEventUtils.descriptors` api notes correction

---

site/views/examples/embedded-media.njk
src/modules/esl-media/README.md
src/modules/esl-media/core/esl-media-provider.ts
src/modules/esl-media/core/esl-media.ts
src/modules/esl-media/providers/brightcove-provider.ts
src/modules/esl-media/providers/html5/audio-provider.ts
src/modules/esl-media/providers/html5/media-provider.ts
src/modules/esl-media/providers/html5/video-provider.ts
src/modules/esl-media/providers/youtube-provider.ts

Closes: #2414 #2415 
- fixed "seekTo leads to no proper behaviour when youtube video is not ready"
- added "ability to provide video initial position (start time)"

feat(esl-media): add ability to provide video initial position (start time)

---

site/.eleventy.js

Temporary fix until `@11ty/eleventy-dev-server` update
See: https://github.com/11ty/eleventy-dev-server/issues/77

chore(site): fix `unhandled in promise` error while site watch process

---

src/modules/esl-carousel/core/esl-carousel.less
src/modules/esl-carousel/plugin/nav/esl-carousel.nav.arrows.less

fix(esl-carousel): add possibility to hide controls according to closest container state

---

src/modules/esl-media-query/README.md
src/modules/esl-media-query/core/esl-media-rule-list.ts

refactor(esl-media-query): deprecate `ESLMediaRuleList.parse`

---

src/modules/esl-mixin-element/test/mixin.prototype.test.ts
src/modules/esl-mixin-element/test/mixin.test.ts
src/modules/esl-mixin-element/ui/esl-mixin-registry.ts

fix(esl-mixin-element): major fix for nested hierarchy mixin disconnection

---

site/views/examples/carousel/centered-siblings.sample.njk
src/modules/esl-carousel/core.ts
src/modules/esl-carousel/core/esl-carousel.less
src/modules/esl-carousel/renderers/esl-carousel.centered.renderer.ts

**Centered Carousel Renderer:**

feat(esl-carousel): add centered renderer

---

e2e/package.json
package-lock.json

Reverts exadel-inc/esl#2570
revert until jest-puppeteer will be compatible

Revert "chore(deps): bump puppeteer from 22.15.0 to 23.0.1"

---

src/modules/esl-anchornav/README.md
src/modules/esl-anchornav/core/esl-anchornav-sticked.ts
src/modules/esl-anchornav/core/esl-anchornav.shape.ts
src/modules/esl-anchornav/core/esl-anchornav.ts

[ESL Anchornav] final update

---

e2e/setup/serializers/image-snapshot.matcher.ts
e2e/setup/serializers/image-snapshot.pocessor.ts
e2e/setup/serializers/image-snapshot.sharp.ts

After test run of a new snapshot matcher implementation, it was discovered that reports became less informative.
The most important things are:
- Missing reports on when two snapshot have mismatching size
- Error messages are less informative

test(e2e): handle sanpshot's size mismatch

---

src/modules/esl-footnotes/README.md
src/modules/esl-footnotes/core/esl-note.ts

BREAKING CHANGE: `tooltip-shown` read-only attribute(prop) replaced with `active` (from `ESLBaseTrigger`)

feat(esl-footnotes): claenup readonly API of `esl-note`

---

site/src/navigation/sidebar/sidebar-content.less
site/src/navigation/sidebar/sidebar-seccondary-nav.less
site/src/navigation/sidebar/sidebar.less
site/views/_includes/navigation/sidebar-item.njk
site/views/_layouts/content.njk
site/views/blogs/ESL v5.0.0 Migartion Guide.md
site/views/core/esl-event-listener/index.njk

A screen of nav panel
Blogs screen:

site: nav updates, 5.0.0 migration guide for blogs section

---

site/views/draft/popup-game.njk
src/modules/esl-popup/README.md
src/modules/esl-popup/core/esl-popup-position.ts
src/modules/esl-popup/core/esl-popup.ts

Added a new attribute `position-origin="outer|inner"` that allows or disallows to overlap of the trigger by a popup window.
Closes: #2746

[🚀 ESL Popup] add position-origin attribute

---

src/modules/esl-utils/dom/traversing.ts

Relates to: #2712
During the implementation of ticket #2712, it was discovered that the combination of checking if a node is an element and using element.contains is frequently needed. To streamline this, an `isSafeContains` utility was introduced.

feat(esl-utils): `safeContains` traverse utility

---

site/views/draft/share-regression.njk
src/modules/esl-share/core/esl-share-popup.ts
src/modules/esl-tooltip/core/esl-tooltip.shape.ts
src/modules/esl-tooltip/core/esl-tooltip.ts

BREAKING CHANGES: disable-arrow attribute removed from ESLTooltip component
Closes: #2782

feat(esl-tooltip): remove disable-arrow attribute

---

src/modules/esl-media/README.md
src/modules/esl-media/core/esl-media-provider.ts
src/modules/esl-media/core/esl-media.ts
src/modules/esl-media/providers/html5/media-provider.ts
src/modules/esl-media/providers/iframe-provider.ts
src/modules/esl-media/providers/youtube-provider.ts

Background video should bot be focusable
Closes: #2816

fix(esl-media): make video unfocusable if `esl-media[role=presentation]`

---

eslint-config/package.json
package-lock.json

Breaking changes in the update:
- remove unnecessary logic - which didn't affect us
- auto-fixing optional chain updates didn't affect us aswel
- comma related changes didn't require any modifications of our code
https://github.com/eslint-stylistic/eslint-stylistic/releases/tag/v3.0.0

chore(deps): bump @stylistic/eslint-plugin from 2.13.0 to 3.0.0

---

src/modules/esl-scrollbar/core/esl-scrollbar.ts
src/modules/esl-tab/core/esl-tabs.ts
src/modules/esl-utils/dom/rtl.ts
src/modules/esl-utils/dom/test/rtl.test.ts

Closes: #2873
I couldn't replicate the behavior where scroll type was any other than 'negative'
Not sure if we need to keep methods if they will always return negative now

refactor(esl-utils): remove `RTL` unnecessary logic

---

src/modules/esl-media/providers/youtube-provider.ts

Closes: #2912
The issue was caused by an interesting behavior of YouTube api:
Basically we were expecting for `PlayerState.ENDED` event to be triggered once video is stopped. But it doesn't. It only happens when video was watched until the end and then automatically stopped.
Behavior is different with a manual stop:
The behavior i got was two event triggered a stop - `PlayerState.UNSTARTED` (-1) and `PlayerState.CUED` (5).
And the [YT API](https://developers.google.com/youtube/iframe_api_reference#Playback_controls) says, that the stopVideo function could put the player into any not-playing state, including ended (0), paused (2), video cued (5) or unstarted (-1).
My guess that unstarted (-1) is triggered every time when video is at 0 seconds and shows sort of the 'preview' state.
I …

fix(esl-media): detect youtube provider stopped state

---

src/modules/esl-scrollbar/core/esl-scrollbar.ts

Closes: #2959
Issue was happening because scrollbar implementation utilizes pageX/Y for scroll calculations and was expecting that these values are not modifiable. But scrolling `html` does actually modify them, and was causing sequence of drag events to quadruple its coordinates. For example: 
The regular scrolling down would look like (+2px, +2px, +3px, + 2px, ....) 
Made html scrolling look like (+2px, +4px, +16px, +32px, +64px).
Instead of substraction scrollX/Y attempt was made to utilize clientX/Y, since it represents viewport coordinates, but it made nested scrollbars break and work in opposite direction if the outer one was modified.

fix(esl-scrollbar): inconsistent dragging if target is `html`

---

src/modules/esl-carousel/README.md
src/modules/esl-carousel/core/esl-carousel.less
src/modules/esl-carousel/renderers/esl-carousel.default.renderer.less
src/modules/esl-carousel/renderers/esl-carousel.default.renderer.ts

Note: the root cause was found in the carousel slide initial styles for dimensions
Closes: #2879

fix(esl-carousel): fix initial CLS for looped carousels

---

package-lock.json
packages/esl-website/package.json

Note: now uses override to use a local version of esl package

chore(deps): update @exadel/ui-playground to version 2.1.0-beta.10

---

packages/esl/src/esl-carousel/core/esl-carousel.errors.ts
packages/esl/src/esl-carousel/core/esl-carousel.renderer.ts
packages/esl/src/esl-carousel/core/esl-carousel.ts
packages/esl/src/esl-carousel/core/esl-carousel.utils.ts
packages/esl/src/esl-carousel/plugin/autoplay/esl-carousel.autoplay.mixin.ts
packages/esl/src/esl-carousel/plugin/dots/esl-carousel.nav.dots.ts
packages/esl/src/esl-carousel/plugin/keyboard/esl-carousel.keyboard.mixin.ts
packages/esl/src/esl-carousel/plugin/nav/esl-carousel.nav.mixin.ts
packages/esl/src/esl-carousel/plugin/relation/esl-carousel.relation.mixin.ts
packages/esl/src/esl-carousel/plugin/touch/esl-carousel.touch.mixin.ts
packages/esl/src/esl-carousel/plugin/wheel/esl-carousel.wheel.mixin.ts
packages/esl/src/esl-carousel/renderers/esl-carousel.css.renderer.ts
packages/esl/src/esl-carousel/renderers/esl-carousel.default.renderer.ts
packages/esl/src/esl-carousel/test/core/esl-carousel.utils.base.test.ts
packages/esl/src/esl-carousel/test/core/esl-carousel.utils.nav.test.ts

✅ DO NOT BE SCARED BY 15 FILES, 
Changes here are really small and granular, just 4 aspects updated here:
- Small fix for the `canNavigate` method
- Related tests added, tests for the whole method moved to a separate file to simplify support (line count limit)
- Add consistent catch with debug log for the `goTo` method + special rejection Error implementation to reduce spam in the console
- Fix `goTo` internal flow to handle collisions and renderer errors correctly

fix(esl-carousel): fix navigation collision logging and handling, fix `canNavigate` behaviour

---

packages/esl-website/src/common/tabs.less
packages/esl/src/esl-tab/core/esl-tab.less
packages/esl/src/esl-trigger/core/esl-base-trigger.ts
packages/esl/src/esl-trigger/core/esl-trigger.less
packages/esl/src/esl-trigger/core/esl-trigger.ts

It is as simple as it could be 
- no warnings from the esl event listener to notify that there is no target for the trigger instance
- simple and clear no-target readonly marker attribute indicating no target found
- default styles so you can clearly understand -something wrong had happened (or you expected that, or you expeded and overrode it in CSS)
The only question I have doubts about right now is - esl-tigger default styles
A) simple but a little bit aggressive in general for abstract trigger `display: none`
B) Some medium customization that you can observe currently in PR
C) Some other thoughts?

feat(esl-trigger): no-target attribute support out of the box, no console warning (default 'disabled' styles)

---

packages/esl/src/esl-popup/core/esl-popup.ts

Fixed issues:
Relates to: #3199

fix(esl-popup): fix ESLPopup is still visible when the trigger is outside the viewport

---

packages/esl/src/esl-carousel/plugin/autoplay/README.md
packages/esl/src/esl-carousel/plugin/autoplay/esl-carousel.autoplay.mixin.ts
packages/esl/src/esl-carousel/test/plugin/autoplay/esl-carousel.autoplay.interaction.test.ts
packages/esl/src/esl-trigger/core/esl-base-trigger.ts
packages/esl/src/esl-trigger/core/esl-trigger.ts
packages/esl/src/esl-utils/dom/events/misc.ts
packages/esl/src/esl-utils/dom/events/test/misc.test.ts

1. Introduce options to specify selector for items that, when active, should disable autoplay and events that stop autoplay:
- `blockingItemsSelector` (optional) – selector (ESLTraversingQuery) for items that, when activated, stop carousel autoplay. Defaults to `esl-share[active], esl-note[active]`.
- `blockingEvents` (optional) – space-separated list of event names that toggle blocking state on the carousel when fired. Defaults to `esl:change:active`. 
2. Update esl-base-trigger and it's instances to dispatch `esl:change:action` by default .
3. Handle empty eventName in `dispatchCustomEvent` function.
Closes: [3349](https://github.com/exadel-inc/esl/issues/3349), [3371](https://github.com/exadel-inc/esl/issues/3371)

feat(esl-carousel):  introduce capabilities to provide custom autoplay restrictions

---

packages/esl/src/esl-alert/core/esl-alert.ts
packages/esl/src/esl-event-listener/core/api.ts
packages/esl/src/esl-event-listener/core/targets/intersection.event.ts
packages/esl/src/esl-event-listener/core/targets/resize.target.event.ts
packages/esl/src/esl-event-listener/core/targets/swipe.target.event.ts
packages/esl/src/esl-event-listener/core/targets/wheel.target.event.ts
packages/esl/src/esl-media-query/core/common/media-shortcuts.ts
packages/esl/src/esl-utils/async/promise.ts
packages/esl/src/esl-utils/dom/rtl.ts
packages/esl/src/esl-utils/environment/device-detector.ts
packages/esl/src/esl-utils/misc.ts
packages/esl/src/esl-utils/misc/array.ts
packages/esl/src/esl-utils/misc/test/array.test.ts
packages/eslint-config/rules/custom/configs.js

BREAKING CHANGE: `ESLAlert.defaultConfig` removed (use `ESLAlert.DEFAULT_PARAMS` instead)
BREAKING CHANGE: `ESLIntersectionEvent.type`, `ESLElementResizeEvent.type`, `ESLSwipeGestureEvent.type` and `ESLWheelEvent.type` removed
BREAKING CHANGE: `ESLEventUtils.getAutoDescriptors` removed (use `ESLEventUtils.descriptors(host, {auto: true})` instead)
BREAKING CHANGE: `ESLEnvShortcuts` alias for `ESLMediaShortcuts` removed
BREAKING CHANGE: `ESLMediaShortcuts.add` and `ESLMediaShortcuts.set` removed (use `ESLMediaShortcuts.set` instead)
BREAKING CHANGE: `PromiseUtils` removed, use individual methods instead
BREAKING CHANGE: `RTLScroll`, `ScrollType`, `testRTLScrollType` removed (IE, Edge < 14 are no longer in support list)
BREAKING CHANGE: `isBot` check removed (no longer works)
BREAKING …

refactor: remove deprecated properties and methods across ESL
