src/modules/esl-utils/fixes/ie-fixes.less
src/modules/esl-utils/misc/format.ts
src/modules/esl-utils/misc/object.ts
src/modules/esl-utils/misc/test/format.test.ts
src/modules/esl-utils/misc/test/object.test.ts

- get/set via path utility
- compile string utility

feat: extend utilities

---

src/modules/esl-base-popup/core/esl-base-popup.ts
src/modules/esl-trigger/core/esl-trigger.ts

Fix click event tracking for BasePopup

fix: fix click event tracking for Popup

---

src/modules/esl-base-popup/core/esl-base-popup.ts
src/modules/esl-trigger/core/esl-trigger.ts

BREAKING CHANGE:
'outsideclick' initiator type replaced with 'outsideaction'

feat!: add last activator feature, fix outside action

---

src/modules/esl-panel/core/esl-panel-stack.less
src/modules/esl-panel/core/esl-panel.ts

refactor: minor fixes of animation

refactor: minor fixes of animation

---

src/modules/esl-utils/decorators/memoize.ts
src/modules/esl-utils/decorators/test/memoize.test.ts

fix: memoize context for class member decoration

---

src/modules/esl-utils/decorators/memoize.ts

IE11 tries to call getter from the prototype key descriptor on Object.defineProperty call.
Lock prevents from the infinite loop on own key definition for class instance member memorization.

fix: 'Stack out of bounds' exception for memoized non static member in IE

---

src/modules/esl-media/providers/brightcove-provider.ts
src/modules/esl-media/providers/iframe-provider.ts
src/modules/esl-media/providers/youtube-provider.ts
src/modules/esl-utils/misc/test/uid.test.ts
src/modules/esl-utils/misc/uid.ts

BREAKING CHANGE: `generateUId` renamed to `randUID`

feat: extend UID utilities

---

pages/src/localdev.ts
pages/views/pages/basic/esl-toggleable.html
src/modules/esl-toggleable/README.md
src/modules/esl-toggleable/core.less
src/modules/esl-toggleable/core/esl-toggleable.less
src/modules/esl-toggleable/core/esl-toggleable.ts

Adds default toggleable styles.
Make active class `open` by default.

fix(esl-toggleable): allow to register toggleable as independent component

---

src/modules/esl-popup/core/esl-popup.ts
src/modules/esl-toggleable/README.md
src/modules/esl-toggleable/core/esl-toggleable.ts
src/modules/esl-utils/dom/events.ts

- Fix toggleable track hover activator
- Add stub methods to event utils
- Small popup updates

bug(esl-toggleable): activator change on track events + small utils update

---

pages/src/common/page.less
pages/views/_includes/header.njk
pages/views/_layouts/html5.njk
pages/views/basic/esl-media.njk
pages/views/index.njk

After adding meta tag 'viewport' a layout change was required, so changes were made to the styles

fix: added meta tag viewport for GH Pages

---

src/modules/esl-scrollbar/core/esl-scrollbar.ts
src/modules/esl-utils/dom/rtl.ts

- update for rtl esl-utils: add normalizeScrollLeft method
- refactor horziontal esl-scrollbar to support rtl

feat(esl-scrollbar): add RTL support

---

src/modules/esl-popup/core/esl-popup-position.ts
src/modules/esl-popup/core/esl-popup.less
src/modules/esl-popup/core/esl-popup.ts
src/modules/esl-utils/dom/element.ts

- move position attribute from popup arrow to popup element
- fix IE issue 'ShadowRoot is undefined'

fix(esl-popup): move position attribute from popup arrow to popup element

---

src/modules/esl-trigger/core/esl-trigger.ts

fix(esl-trigger): fix incorrect tap handling on mobile devices

---

pages/src/common/page.less
pages/src/header/header.less
pages/views/_includes/header-menu.njk
pages/views/_includes/header.njk
pages/views/samples/image.njk
src/modules/esl-image/core/esl-image.ts
src/modules/esl-media/README.md
src/modules/esl-media/core/esl-media.ts
src/modules/esl-panel-group/README.md
src/modules/esl-panel/README.md
src/modules/esl-panel/core/esl-panel.ts
src/modules/esl-scrollbar/core/esl-scrollbar.ts
src/modules/esl-toggleable/core/esl-toggleable.ts

- ESLPanel: fix reflow on show animation
- ESLToggelable: implement discussed approach for outside listener handler
- Doc fixes. Note: there is one more item to discuss in https://github.com/exadel-inc/esl/issues/357
- Add overall and update fallback time for gh-pages header menu

fix: toggleable and panel animation fixes

---

src/modules/esl-a11y-group/README.md
src/modules/esl-alert/README.md
src/modules/esl-base-element/README.md
src/modules/esl-footnotes/README.md
src/modules/esl-forms/esl-select-list/README.md
src/modules/esl-forms/esl-select/README.md
src/modules/esl-image/README.md
src/modules/esl-media-query/README.md
src/modules/esl-media/README.md
src/modules/esl-panel-group/README.md
src/modules/esl-panel/README.md
src/modules/esl-popup/README.md
src/modules/esl-scrollbar/README.md
src/modules/esl-tab/README.md
src/modules/esl-toggleable/README.md
src/modules/esl-traversing-query/README.md
src/modules/esl-trigger/README.md
src/modules/esl-utils/README.md

we need to change the links since we need to follow them without leaving our site

docs: replace relative links to absolute

---

pages/src/footer/footer.less
pages/views/_includes/footer-menu.njk
pages/views/_includes/footer.njk

docs: fix footer style

---

src/modules/esl-popup/core/esl-popup.ts

Fixed incorrect popups arrow position settings in the case when esl-popup instance change position.

fix(esl-popup): fix arrow position for adjacent axis

---

README.md
package.json
pages/.eleventy.js
pages/11ty/markdown.shortcut.js
pages/static/tools/config.yml
pages/views/_data/site.json
src/modules/esl-a11y-group/README.md
src/modules/esl-alert/README.md
src/modules/esl-base-element/README.md
src/modules/esl-footnotes/README.md
src/modules/esl-forms/esl-select-list/README.md
src/modules/esl-forms/esl-select/README.md
src/modules/esl-image/README.md
src/modules/esl-media-query/README.md
src/modules/esl-media/README.md
src/modules/esl-panel-group/README.md
src/modules/esl-panel/README.md
src/modules/esl-popup/README.md
src/modules/esl-scrollbar/README.md
src/modules/esl-tab/README.md
src/modules/esl-toggleable/README.md
src/modules/esl-traversing-query/README.md
src/modules/esl-trigger/README.md
src/modules/esl-utils/README.md

Updates to build everything for new custom domain

chore(gh-pages): custom domain settings and updates

---

pages/views/_layouts/popup.njk
src/modules/esl-popup/core/esl-popup-position.ts
src/modules/esl-popup/core/esl-popup.less

fix(esl-poup): fix popup positioning

---

src/modules/esl-traversing-query/core/esl-traversing-query.ts
src/modules/esl-traversing-query/test/esl-traversing-query.test.ts

feat(esl-traversing-query): add ability to restrict global scope

---

src/modules/esl-traversing-query/core/esl-traversing-query.ts
src/modules/esl-traversing-query/test/esl-traversing-query.test.ts

Closes: #522
Duplicates #639 with a proper base

Extend esl traversing query

---

pages/11ty/hidden.filter.js
pages/11ty/ignored.filter.js
pages/views/_includes/navigation/footer-menu.njk
pages/views/_layouts/collection-grid.njk
pages/views/components/index.njk
pages/views/examples/index.njk
pages/views/utils/index.njk

In this PR i renamed ignore filter into hidden

chore(gh-pages): rename ignore filter

---

src/modules/esl-popup/core.less
src/modules/esl-popup/core.mixin.less
src/modules/esl-popup/core/esl-popup.less

To make it easier to initialize styles on the consumer side, a mixin was created.

feat(esl-popup): create esl-popup-init mixin to make it easier to initialize styles

---

pages/views/examples/popup-scroll-parents.njk
pages/views/examples/popup-transition.njk
pages/views/examples/popup.njk
src/modules/esl-popup/core/esl-popup.ts
src/modules/esl-utils/dom/rect.ts

In scope of this PR:
- remade demo pages
- added isEqual method to Rect class
- added updating position on transitions
- added descriptions of class methods

feat(esl-popup): update position on transitions

---

src/modules/esl-utils/dom/test/rect.test.ts

In this PR i covered rect.ts with tests

test(esl-utils): rect.ts test coverage

---

src/modules/esl-animate/core.ts
src/modules/esl-animate/core/esl-animate.shape.ts

Add tsx shape types support for esl-animate
Closes: #708

feat(esl-animate): add jsx/tsx support

---

src/modules/esl-toggleable/core/esl-toggleable.shape.ts
src/modules/esl-toggleable/core/esl-toggleable.ts

- fix wrong and missing TSX shape attributes
- fix `_onOutsideAction` and `_onClick` signature
- `keypress` event now also considered as an outside

feat(esl-toggleable): small enchancements

---

src/modules/esl-toggleable/README.md
src/modules/esl-toggleable/core/esl-toggleable.shape.ts
src/modules/esl-toggleable/core/esl-toggleable.ts

Add auto id to ESLToggleable component (will set if there isn't user's id).
User can also disable auto id.

feat(esl-toggleable): add auto id

---

src/modules/esl-utils/async/test/debounce.test.ts

In the scope of this PR i fixed issue, where test was throwing an unhandled promise rejection

bugfix: Tests unhandled rejection fix 

---

build/catlog.js
package-lock.json
package.json
pages/.eleventy.js
pages/11ty/env.config.js
pages/11ty/markdown.shortcut.js
pages/views/_data/env.js

- 11ty updated to 1.0.0
- chalk replaced with [kleur](https://github.com/lukeed/kleur)

chore: update 11ty to 1.0.0

---

src/modules/esl-footnotes/core/esl-footnotes-data.ts
src/modules/esl-footnotes/core/esl-footnotes.ts
src/modules/esl-footnotes/core/esl-note.ts

In the scope of this PR:
- fixed sorting of notes
- fixed the corruption of the note's content

esl-footnotes fixes

---

src/modules/esl-media/core/esl-media.ts

style: style/performance improvement for condition query

---

src/modules/esl-footnotes/core/esl-note.ts

Added activate timeout to have time to show content with this note

Footnotes: add activate timeout

---

pages/views/examples/footnotes.njk
src/modules/esl-footnotes/core/esl-note.ts
src/modules/esl-popup/core/esl-popup.ts

Added param to pass container element to popup

Popup: add containerEl param to action params

---

pages/views/examples/tabs.njk
src/modules/esl-panel-group/README.md
src/modules/esl-panel-group/core/esl-panel-group.less
src/modules/esl-panel-group/core/esl-panel-group.shape.ts
src/modules/esl-panel-group/core/esl-panel-group.ts
src/modules/esl-panel/README.md
src/modules/esl-panel/core/esl-panel.shape.ts
src/modules/esl-panel/core/esl-panel.ts

feat: ESLPanel and ESLPanelGroup fallback duration retirement

---

pages/src/search/search-script.ts

In the scope of this PR I fixed issue with website not working in IE. The issue was resolved by adding "src" in import path and fix was verified in IE browser.

fix(gh-pages): change import in gss

---

src/modules/esl-panel-group/core/esl-panel-group.ts
src/modules/esl-panel/core/esl-panel.ts

fix(esl-panel-group): add `capturedBy` and fix 'esl:after:show' dispatch

---

pages/src/esl-media-demo/test-media-source.ts
pages/src/esl-media-demo/test-media.less
pages/src/esl-media-demo/test-media.ts
pages/views/components/esl-media.njk
pages/views/examples/embedded-audio.njk
pages/views/examples/embedded-video.njk

Refactor test components according the main approach

refactor(gh-pages): refactoring of test media components

---

src/modules/esl-toggleable/README.md
src/modules/esl-toggleable/core/esl-toggleable.ts

fix(esl-toggleable): fix double `esl:` prefix for esl-toggleable `esl:refresh` dispatching

---

src/modules/esl-utils/dom/rect.ts
src/modules/esl-utils/dom/test/rect.test.ts

In the scope of this PR I modified grow and shrink methods of Rectangle class to accept incrementers/decrementers separately for x and y axis

feat(esl-utils/rect): ability to grow/shrink axis

---

src/modules/esl-popup/core/esl-popup.ts

In the scope of PR:
- add extended offsetContainer configuration to set up different values for offset by x and offset by y

feat(esl-popup): add extended offsetContainer configuration

---

src/modules/esl-toggleable/core/esl-toggleable.ts
src/modules/esl-utils/dom/test/traversing.test.ts
src/modules/esl-utils/dom/traversing.ts

In the scope of this PR I made ability to pass additional options with the esl:show:request
Closes: #928

feat(esl-togglable): show:request additional data

---

src/modules/esl-media-query/core/conditions/media-query-condition.ts
src/modules/esl-media-query/core/conditions/media-query-containers.ts
src/modules/esl-utils/abstract/event-target.ts
src/modules/esl-utils/dom/events.ts
src/modules/esl-utils/dom/events/listener.ts
src/modules/esl-utils/dom/events/misc.ts
src/modules/esl-utils/dom/events/target.ts
src/modules/esl-utils/dom/events/test/target.test.ts

fix(esl-utils): event listener utils bugfixes

---

.github/workflows/commit.yml
.github/workflows/pages.yml
.github/workflows/release.yml
.github/workflows/test-pack.yml
.github/workflows/validate.yml

Updated `setup-node` action due to workflows build crash
Closes: #1031

chore: update `setup-node` action due to workflows build crash

---

src/modules/esl-media-query/core/esl-media-rule-list.ts
src/modules/esl-media-query/test/esl-media-rule-list.test.ts

add condition for case if data in `valueList`  less than in `queries`
Closes: #1044

feat(esl-media-query): normalize data instead of fail

---

src/modules/esl-forms/esl-select/core/esl-select.ts

Closes: https://github.com/exadel-inc/esl/issues/1068

feat(esl-select): add dropdown-class to observed attributes

---

.husky/pre-commit
.lintstagedrc.yml
package-lock.json
package.json

In the scope of this PR I added lint-staged integration in order to run pre-commit checks only on files that are staged. This small change will speed up committing process

chore(lint): lint staged integration

---

src/modules/esl-media-query/core/conditions/media-query-condition.ts
src/modules/esl-media-query/core/conditions/media-query-containers.ts
src/modules/esl-media-query/core/esl-media-rule-list.ts
src/modules/esl-utils/dom/events/target.ts

In the scope of this PR I reworked public API for SyntheticEventTarget so future changes to the class won't be affecting other components

refactor(esl-utils): rework public api for SyntheticEventTarget

---

pages/views/examples/toggleable.njk
src/modules/esl-trigger/README.md
src/modules/esl-trigger/core/esl-trigger.shape.ts
src/modules/esl-trigger/core/esl-trigger.ts

[Closes #1110 ](https://github.com/exadel-inc/esl/issues/1110)

feat(esl-trigger): add `ignore-esc` attribute

---

src/modules/esl-panel-group/README.md
src/modules/esl-panel-group/core/esl-panel-group.shape.ts
src/modules/esl-panel-group/core/esl-panel-group.ts

Part of [#1132](https://github.com/exadel-inc/esl/issues/1132)

fix(esl-panel-group): change `no-animate` API

---

pages/src/common/badge.less
pages/src/common/colors.less
pages/views/_includes/landing/blogs.njk
pages/views/_includes/navigation/sidebar-item.njk
pages/views/_layouts/collection-grid.njk
pages/views/_layouts/content.njk
pages/views/blogs/index.njk
pages/views/core/esl-mixin-element.njk

refactor(gh-pages): add `new` badge

---

src/modules/esl-scrollbar/core/esl-scrollbar.less

Issue: https://github.com/exadel-inc/esl/issues/1197

fix(esl-scrollbar): remove unnecessary width

---

pages/src/common/badge.less
pages/views/_includes/navigation/sidebar-item.njk

-Change size of badges
- Remove badges from `Drafts`

feat(gh-pages): remove badges from "Drafts" section

---

pages/views/draft/accordion-regression.njk
src/modules/esl-panel-group/core/esl-panel-group.ts

feat(esl-panel-group): add ability to specify the strategy of closing panels in case the max-open-items limit is reached

---

src/modules/esl-tab/README.md
src/modules/esl-tab/core/esl-tabs.less
src/modules/esl-tab/core/esl-tabs.scrollable.less
src/modules/esl-tab/core/esl-tabs.ts

[Closes #1210](https://github.com/exadel-inc/esl/issues/1210)

fix(esl-tabs): fix alignment behavoir

---

src/modules/esl-animate/core/esl-animate-service.ts
src/modules/esl-animate/test/animate.mixin.test.ts
src/modules/esl-animate/test/animate.service.test.ts
src/modules/esl-animate/test/animate.test.ts
src/modules/esl-animate/test/intersectionObserver.mock.ts

Tests are covering the following areas of module:
ESL Animate Service smoke (basic + options)
ESL Animate Element unit (wrapper) tests
ESL Animate Mixin unit (wrapper) tests
#1280

test(esl-animate): cover esl-animate module parts with tests and code improvements

---

pages/src/common/markdown.less
src/modules/esl-event-listener/README.md
src/modules/esl-event-listener/core/api.ts
src/modules/esl-event-listener/core/descriptors.ts
src/modules/esl-event-listener/core/listener.ts
src/modules/esl-event-listener/test/descriptor.test.ts
src/modules/esl-mixin-element/test/mixin.listener.test.ts
src/modules/esl-utils/misc/object/types.ts

docs(esl-event-listener): `esl-event-listener` module updated documentation & type fixes

---

src/modules/esl-forms/esl-select/core/esl-select-dropdown.ts

appendChild was forcing disconnectedCallback to be called
Closes #1421

bugfix(esl-select): activator lost on dropdown hide

---

.github/workflows/validate.yml
package.json

[Code Climate](https://codeclimate.com) integration proposal

chore: Code Climate integration to the CI process

---

src/modules/esl-event-listener/README.md
src/modules/esl-event-listener/core/api.ts
src/modules/esl-event-listener/core/descriptors.ts
src/modules/esl-event-listener/core/listener.ts
src/modules/esl-event-listener/core/targets/decorated.target.ts
src/modules/esl-event-listener/core/targets/resize.adapter.ts
src/modules/esl-event-listener/core/types.ts

Please review the documentation carefully there were new chapters created

style(esl-event-targets): docs and code reformating

---

src/modules/esl-alert/core/esl-alert.ts
src/modules/esl-base-element/core/esl-base-element.ts
src/modules/esl-base-element/test/element.listener.test.ts
src/modules/esl-footnotes/core/esl-note.ts
src/modules/esl-forms/esl-select-list/core/esl-select-item.ts
src/modules/esl-forms/esl-select-list/core/esl-select-list.ts
src/modules/esl-mixin-element/ui/esl-mixin-element.ts
src/modules/esl-toggleable/core/esl-toggleable.ts
src/modules/esl-toggleable/test/toggleable.request.test.ts
src/modules/esl-trigger/test/esl-trigger.a11y.test.ts

Revert "feat(esl-core): make this.constructor strictly typed for `ESLBaseElement` and `ESLMixinElement`"

---

src/modules/esl-event-listener/core/listener.ts

fix(esl-event-listener): ehnance checking of event target instance when delegating

---

src/modules/esl-event-listener/test/targets/decorator.test.ts
src/modules/esl-utils/async/test/throttle.test.ts
src/modules/esl-utils/async/throttle.ts

Throttle looked to be handled incorrectly
#1535

fix(esl-utils): incorrect throttle behaviour

---

src/modules/draft/esl-carousel/core/esl-carousel.ts
src/modules/draft/esl-carousel/plugin/esl-carousel-link.plugin.ts
src/modules/esl-animate/core/esl-animate.ts
src/modules/esl-base-element/core/esl-base-element.ts
src/modules/esl-footnotes/core/esl-note.ts
src/modules/esl-forms/esl-select-list/core/esl-select-item.ts
src/modules/esl-forms/esl-select-list/core/esl-select-list.ts
src/modules/esl-forms/esl-select/core/esl-select.ts
src/modules/esl-image/core/esl-image.ts
src/modules/esl-media/core/esl-media.ts
src/modules/esl-mixin-element/ui/esl-mixin-element.ts
src/modules/esl-panel-group/core/esl-panel-group.ts
src/modules/esl-scrollbar/core/esl-scrollbar.ts
src/modules/esl-tab/core/esl-tabs.ts
src/modules/esl-toggleable/core/esl-toggleable.ts
src/modules/esl-trigger/core/esl-trigger.ts
src/modules/esl-utils/abstract/component.ts

Note: `attributeChangeCallback` explicitly defined in `ESLBaseElement`

feat: `ESLBaseComponent` interface shared between `ESLMixinElement` and `ESLBaseElement`

---

src/modules/esl-event-listener/core/descriptors.ts

style(esl-event-listener): regroup event listener code (#1449)

---

src/modules/esl-footnotes/README.md
src/modules/esl-footnotes/core/esl-footnotes.ts
src/modules/esl-footnotes/core/esl-note.ts

feat(esl-footnotes): add support of the anchor relationship between note and footnote for the print version

---

src/modules/esl-forms/esl-select/core/esl-select-dropdown.ts
src/modules/esl-forms/esl-select/core/esl-select-renderer.ts
src/modules/esl-forms/esl-select/core/esl-select.ts

epic(esl-select): reworked using esl-popup (#1321)

---

src/modules/esl-footnotes/core/esl-note.less
src/modules/esl-footnotes/core/esl-note.ts

fix(esl-footnotes): remove the possibility of setup esl-note anchor markup conditionally

---

src/modules/esl-base-element/core/esl-base-element.ts
src/modules/esl-base-element/test/element.test.ts

Closes: #1804
Introduced in #1766

fix(esl-base-element): fix redefine tag feature (existing component receives incorrect tag name)

---

src/modules/esl-utils/dom/events/target.ts
src/modules/esl-utils/misc/uid.ts

<body>
make __esl_sequanse__ a private key using Symbol
Closes: #1866

feat(esl-utils): make __esl_sequanse__ a private key using Symbol

---

src/modules/esl-event-listener/core/listener.ts
src/modules/esl-media/core/esl-media.ts
src/modules/esl-scrollbar/core/esl-scrollbar.ts
src/modules/esl-traversing-query/core/esl-traversing-query.ts
src/modules/esl-trigger/core/esl-trigger.ts
src/modules/esl-utils/abstract/dom-target.ts
src/modules/esl-utils/abstract/test/dom-target.test.ts
src/modules/esl-utils/dom/api.ts
src/modules/esl-utils/dom/scroll/parent.ts
src/modules/esl-utils/dom/test/api.test.ts
src/modules/esl-utils/dom/visible.ts
src/modules/esl-utils/misc/object/test/types.test.ts
src/modules/esl-utils/misc/object/types.ts

fix: support for items being moved from iframe using unified `isElement` check

---

pages/src/esl-swipe-demo/esl-swipe-demo-area.less
pages/src/esl-swipe-demo/esl-swipe-demo-area.ts
pages/views/draft/swipe-demo.njk
src/modules/esl-event-listener/README.md
src/modules/esl-event-listener/core/targets/swipe.target.event.ts
src/modules/esl-event-listener/core/targets/swipe.target.ts
src/modules/esl-event-listener/test/targets/swipe.test.ts

feat(swipe-target): add angle to swipe event, simplify API

---

package-lock.json
pages/11ty/htmlmin.transform.js
pages/package.json

chore(site): migrate `html-minifier` to `html-minifier-terser` (supported continuation for initial plugin)

---

src/modules/esl-traversing-query/README.md

<body>
add note recarding scope, missing examples
Closes: #1864

docs(esl-traversing-query): improve documentation for esl-traversing-query

---

src/modules/esl-popup/core/esl-popup.ts
src/modules/esl-toggleable/core/esl-toggleable.ts

Closes https://github.com/exadel-inc/esl/issues/1677
NOTE: creataed as an alternative to https://github.com/exadel-inc/esl/pull/1679 initial implementation

refactor(esl-toggleable): update API with before show/hide livecycle hooks

---

pages/views/draft/swipe-demo.njk
src/modules/esl-event-listener/README.md
src/modules/esl-event-listener/core/targets/swipe.target.event.ts
src/modules/esl-event-listener/core/targets/swipe.target.ts
src/modules/esl-event-listener/test/targets/swipe.test.ts

fix(esl-event-utils): `ESLSwipeGestureTarget` target prevents inside element actions

---

src/modules/esl-popup/core/esl-popup.ts

feat(esl-popup): internal ESLPopup implementation updated to use ESLEventListeners; usage of cached properties reduced

---

src/modules/esl-scrollbar/core/esl-scrollbar.ts

fix(esl-scrollbar): fix esl:change:scroll event handler invoked before scrollbar updates

---

src/modules/esl-utils/async/test/aggregate.test.ts

test(esl-utils): improve `aggregated` tests

---

site/views/draft/multi-carousel.njk
site/views/examples/carousel.njk
src/modules/esl-carousel/README.md
src/modules/esl-carousel/plugin/touch/esl-carousel.touch.mixin.ts
src/modules/esl-event-listener/core/targets/swipe.target.event.ts
src/modules/esl-utils/misc/enum.ts

refactor ESLCarouselTouchMixin (add swipe support)
Closes #2162

feat(esl-carousel): add swipe support for ESLCarouselTouchMixin

---

site/views/blogs/ESL v4.15.0.md
site/views/blogs/UIP 2.0.0 (April).md

docs(site): add UIP announce for release 4.15.0 build

---

src/modules/esl-utils/decorators/attr.ts
src/modules/esl-utils/decorators/test/attr.test.ts
src/modules/esl-utils/dom/attr.ts
src/modules/esl-utils/dom/test/attr.test.ts

Porting 
- #2184
- #2228
for 4-th version

[maintain] Porting `attr` related changes for `4.16.0`

---

src/modules/esl-event-listener/core/targets/intersection.event.ts
src/modules/esl-event-listener/core/targets/intersection.target.ts
src/modules/esl-event-listener/test/targets/intersection.test.ts
src/modules/esl-popup/core/esl-popup.ts

Closes #2300 
Not sure we need to handle intersection ratio cases, since we weren't handling it before. But maybe it needs to be changed.

feat(esl-event-listener): separate intersection events

---

site/views/examples/animate.njk

fix(site): `esl-animate` example page wrong animation

---

src/modules/esl-utils/dom/script.ts
src/modules/esl-utils/dom/test/script.test.ts

add the ability to use additional attributes in loadScript utility

---

src/modules/esl-event-listener/core/types.ts
src/modules/esl-utils/decorators/listen.ts

feat(esl-utils): make DelegatedEvent equal too `DelegatedEvent<Event>`, fix types compatibility

---

src/modules/esl-alert/core/esl-alert.ts
src/modules/esl-footnotes/core/esl-note.ts
src/modules/esl-image/core/esl-image-iobserver.ts
src/modules/esl-media-query/core/common/env-shortcuts.ts
src/modules/esl-media-query/core/common/screen-dpr.ts
src/modules/esl-media-query/test/esl-media-query.test.ts
src/modules/esl-toggleable/core/esl-toggleable.ts
src/modules/esl-trigger/core/esl-base-trigger.ts
src/modules/esl-trigger/test/esl-trigger.actions.test.ts
src/modules/esl-utils/fixes/viewport.ts
src/modules/esl-utils/test/deviceDetector.mock.ts

refactor(esl-utils): remove `DeviceDetector` use from code

---

site/views/examples/carousel.marquee.njk
site/views/examples/carousel.njk
src/modules/esl-carousel/core/esl-carousel.less
src/modules/esl-carousel/plugin/nav/esl-carousel.nav.arrows.less

refactor(esl-carousel): replace default arrow implementation with a clip-path

---

src/modules/esl-carousel/core/esl-carousel.less
src/modules/esl-carousel/plugin/touch/esl-carousel.touch.mixin.ts

However it needs to be tested (on devices, in real cases)

refactor(esl-carousel): touch action rewritten to use `PointerEvents` API

---

e2e/setup/element/scenarios.attr.ts
e2e/setup/element/scenarios.class.ts
e2e/setup/scenarios.ts

test(e2e): attribute and class directives

---

e2e/setup/element/scenarios.xpath.ts
e2e/setup/scenarios.ts

test(e2e): finding element by xpath

---

src/modules/esl-event-listener/README.md
src/modules/esl-event-listener/core/listener.ts
src/modules/esl-event-listener/core/types.ts
src/modules/esl-event-listener/test/listener.unsubscribe.test.ts

feat(esl-event-listener): add a `group` key to process batch subscription operations

---

src/modules/esl-popup/core/esl-popup.ts
src/modules/esl-utils/misc/format.ts
src/modules/esl-utils/misc/test/format.test.ts

fix(esl-popup): it is not possible to set the offset-arrow to 0

---

src/modules/esl-scrollbar/core/esl-scrollbar.less
src/modules/esl-scrollbar/core/esl-scrollbar.ts

refactor(esl-scrollbar): drag action rewritten to use `PointerEvent` API

---

src/modules/esl-panel-group/README.md
src/modules/esl-panel-group/core/esl-panel-group.ts
src/modules/esl-panel/core/esl-panel.ts

fix(esl-panel): fix the falsy state of animation in the default open panel in esl-panel-group

---

eslint/package.json
eslint/src/core/check-version.ts
eslint/src/index.ts
package-lock.json

fix(lint): notify about version differences for `eslint-plugin-esl`

---

.eslintrc.yml
linting/site.eslintrc.yml
site/views/_includes/navigation/footer.njk

Closes: https://github.com/exadel-inc/esl/issues/1925

chore(site): add a rule to disallow direct imports from library source in subpackages

---

src/modules/esl-carousel/core/esl-carousel.events.ts
src/modules/esl-carousel/core/esl-carousel.less
src/modules/esl-carousel/core/esl-carousel.slide.ts
src/modules/esl-carousel/core/esl-carousel.ts
src/modules/esl-carousel/plugin/autoplay/esl-carousel.autoplay.mixin.ts
src/modules/esl-carousel/plugin/esl-carousel.plugin.ts
src/modules/esl-carousel/plugin/wheel/esl-carousel.wheel.mixin.ts
src/modules/esl-event-listener/core/targets/wheel.target.ts
src/modules/esl-event-listener/test/targets/wheel.test.ts

Note: API updates (single option param) for Carousel PLuging will be rediscussed on weekly and implemented separately

feat(esl-carousel + esl-event-listener): Bunch of updates for carousel API, wheel plugin and core wheel target 

---

eslint/src/core/check-version.ts
eslint/src/core/deprecated-class-method.ts
eslint/src/core/log.ts
eslint/src/index.ts
eslint/src/rules/4/deprecated.media-rule-list-parse.ts
eslint/test/deprecated-class-method.test.ts

refactor(lint): fix deprecated-4/media-rule-list-parse rule according live testing notes and introduced utilities

---

site/src/banner/banner.less
site/src/banner/banner.ts
site/src/common/alert.less
site/src/common/colors.less
site/src/common/markdown.less
site/src/navigation/footer/footer-compact.less
site/views/_data/banner.yml
site/views/_includes/navigation/banner.njk
site/views/_includes/navigation/footer-compact.njk

Closes: #2380
Preview:
https://github.com/user-attachments/assets/2acb5a87-f773-4fea-b68e-48982bc891b9
Screen:

refactor(site): update site contribution banner

---

eslint.config.js
eslint/jest.config.js
eslint/package.json
eslint/src/core/deprecated-alias.ts
eslint/src/core/deprecated-path.ts
eslint/src/index.ts
eslint/src/rules/4/all.rules.ts
eslint/src/rules/5/all.rules.ts
eslint/test/deprecated-alias.invalid.test.ts
eslint/test/deprecated-alias.valid.test.ts
eslint/test/deprecated-class-method.test.ts
package-lock.json
package.json

feat(lint): adapt eslint plugin to be used with ESLint 9

---

src/modules/esl-drag-to-scroll/core/esl-drag-to-scroll.mixin.ts

Cosmetic: update methods visibility for inheritors
Continuation of https://github.com/exadel-inc/esl/pull/2710

fix(esl-drag-to-scroll): fix propagation of the click if drag detected

---

src/modules/esl-carousel/core.ts
src/modules/esl-carousel/core/esl-carousel.shape.ts
src/modules/esl-carousel/plugin/dots/esl-carousel.nav.dots.shape.ts

fix(esl-carousel): esl-carousel tag is not declared to be used in TSX

---

src/modules/esl-tooltip/core/esl-tooltip.ts

fix(esl-tooltip): fix tooltip arrow disappearing

---

src/modules/esl-footnotes/core/esl-note.ts

fix(esl-footnotes): fix improper note highlighting

---

src/modules/esl-popup/README.md
src/modules/esl-popup/core/esl-popup.shape.ts
src/modules/esl-popup/core/esl-popup.ts

ESLPopup: add offset-trigger attribute

---

site/views/examples/embedded-media.njk
src/modules/esl-media/core/esl-media-container.less
src/modules/esl-media/core/esl-media.less

Available classes:
- `esl-media-left`
- `esl-media-right`
- `esl-media-top`
- `esl-media-bottom`

fix(esl-media): fix conflict of alignment classes, move definition to the main mixin

---

site/views/dev/carousel-cls.njk
src/modules/esl-carousel/renderers/esl-carousel.default.renderer.less
src/modules/esl-carousel/renderers/esl-carousel.default.renderer.ts
src/modules/esl-carousel/renderers/esl-carousel.grid.renderer.less

fix(esl-carousel): fix initial rendering layout shift to eliminate CLS degradation

---

src/modules/esl-image-utils/core/esl-image-container.mixin.ts

fix(esl-image-utils): omit console warnings in case of missing inner image

---

src/modules/esl-media/core/esl-media-provider.ts
src/modules/esl-media/core/esl-media.ts

fix(esl-media): add play preconditions support for toggle method

---

src/modules/esl-event-listener/core/descriptors.ts
src/modules/esl-event-listener/test/descriptor.test.ts

fix(esl-event-listener): subscribe descriptors if the host is function/class

---

package-lock.json
packages/eslint-config/README.md
packages/eslint-config/package.json
packages/eslint-config/rules/lang/typescript.js

`eslint-import-resolver-typescript` added as a direct dependecy of ESL ESLint config

fix(eslint-config): fix import plugin configuration

---

packages/esl-website/views/examples/animate.njk
packages/esl/src/esl-animate/core/esl-animate-service.ts

fix(esl-animate): fix esl-animate does not work with repeat + ratio 1

---

package-lock.json
package.json
packages/esl-website/package.json
packages/eslint-config/package.json
packages/snapshot-tests/package.json

Updated:
- webpack to 5.99.9
- eslint to 9.27.0
- sharp to 0.34.2
- ts-jest to 29.3.4

chore(deps): update dependencies to latest versions

---

packages/esl/src/esl-mixin-element/ui/esl-mixin-attr.ts
packages/esl/src/esl-mixin-element/ui/esl-mixin-registry.ts

fix(esl-mixin-element): fix ESLMixinRegistry instance duplicate due to creation in separate context

---

packages/esl/src/esl-carousel/plugin/autoplay/README.md
packages/esl/src/esl-carousel/plugin/autoplay/esl-carousel.autoplay.mixin.ts

feat(esl-carousel): add out of the box viewport visibility control for ESL Carousel autoplay plugin

---

packages/esl/src/esl-media/README.md
packages/esl/src/esl-media/core/esl-media-iobserver.ts
packages/esl/src/esl-media/core/esl-media-manager.ts
packages/esl/src/esl-media/core/esl-media.shape.ts
packages/esl/src/esl-media/core/esl-media.ts
packages/esl/src/esl-media/test/base-provider.livecycle.test.ts
packages/esl/src/esl-media/test/media-manager.test.ts

Big thanks to @NastaLeo for update ❤️

fix(esl-media): fix ESLMedia play-in-viewport observes viewport intersection ratio threshold incorrectly

---

packages/esl/src/esl-carousel/core/esl-carousel.utils.ts
packages/esl/src/esl-carousel/plugin/wheel/esl-carousel.wheel.mixin.ts

fix(esl-carousel): fix wheel event handling (wheel ignores next slide direction)

---

packages/esl-website/11ty/date.filter.js
packages/esl-website/src/landing/newsline/newsline.ts
packages/esl-website/src/site.ts
packages/esl-website/views/_includes/landing/newsline-item.njk
packages/esl-website/views/_includes/landing/newsline.njk

Closes: #3258 
Instead of updating label only once per build the logic has transferred to UI level

refactor(site): news section labels refresh

---

packages/esl-website/src/navigation/sidebar/sidebar-primary-nav.less
packages/esl-website/views/_includes/navigation/sidebar.njk

chore(site): update sidebar links divider to common style
